[[language]]
name = "okabe"
scope = "source.okabe"
injection-regex = "ok"
file-types = [
  "ok"
]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "okabe"
source = { git = "https://github.com/vv52/tree-sitter-okabe", rev = "986dce4273902cf7340a63b73e34951a1f2e175b" }
